version: '3'

services:
  bici-otp:
    container_name: bici-otp
    build: .
    volumes:
      - ./data:/usr/local/lib/data
    # ports:
    #  - 8095:8080
    restart: unless-stopped

networks:
  default:
    name: trufi-server
